# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dftomat
#' @description Converts selected columns of `data.frame` to a `matrix`
#' @md
#' @param obj `data.frame`
#' @param cols `character` `vector` of columns to convert to matrix
#' @export
#' @return A `matrix`
#' thedf <- data.frame(ID=rep(c('A', 'B'), length.out=10), A=sample(10), B=rnorm(10), C=sample(10))
#' dftomat(thedf, cols=c('A'))
#' dftomat(thedf, cols=c('A', 'B'))
#' dftomat(thedf, cols=c('A', 'B', 'C'))
dftomat <- function(obj, cols) {
    .Call(`_distancethreshold_dftomat`, obj, cols)
}

#' @title rank_of
#' @description Find rank of an element in a sorted array
#' @author Michael Beigelmacher
NULL

#' @title threshold_distance_compute2
#' @description Computes distance between points in one object to another object
#' @author Michael Beigelmacher
#' [[Rcpp::export]]
NULL

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_distancethreshold_RcppExport_registerCCallable', PACKAGE = 'distancethreshold')
})
